use_frameworks!

platform :ios, '11.0'

target 'ViewSizeCalculation_Example' do
  pod 'ViewSizeCalculation', :path => '../'

  target 'ViewSizeCalculation_Tests' do
    inherit! :search_paths

    
  end
end
